site: 2JAE22 (Jaegun Lee)

url: 
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name

  projects:
    output: true
    permalink: /projects/:path

  archives:
    output: true
    permalink: /archives/:path

  awards:                # ← 이 줄 추가
    output: true
    permalink: /awards/:path

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - 
    scope:
      path: ""
      type: "archives"
    values:
      layout: "archive"
  -
    scope:
      path: ""
      type: "awards"
    values:
      layout: "award"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed


plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

future: true

timezone: Asia/Seoul
