name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # main 브랜치에서 배포 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 기본 GITHUB_TOKEN 제거

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.7'

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Check if GH_PATH is set
        run: |
          if [[ -z "${{ secrets.GH_PATH }}" ]]; then
            echo "❌ GH_PATH is not set"
            exit 1
          else
            echo "✅ GH_PATH is set"
          fi

      - name: Deploy to GitHub Pages (`gh-pages` 브랜치)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan gh-pages  # 새 브랜치 생성 (기존 기록 제거)
          git rm -rf .  # 기존 파일 삭제
          mv _site/* .  # 빌드된 파일을 루트로 이동

          git add .
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "🚀 Deploy Jekyll site"
          git push -f origin gh-pages  # 강제 푸시 (브랜치 초기화)
