name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # main 브랜치에 push하면 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.7'  # 로컬에서 사용하는 Ruby 버전과 동일하게 설정

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      # - name: Deploy to GitHub Pages
      #   run: |
      #     touch _site/.nojekyll  # GitHub Pages가 _site 폴더를 그대로 읽게 함
      #     cp -r _site/* .  # _site 내용 메인 브랜치 루트로 이동
      #     git config --global user.name "${{ github.actor }}"
      #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add .
      #     git commit -m "🚀 Auto-deploy Jekyll site"
      #     git push origin main
      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PATH }}@github.com/2JAE22/2JAE22.github.io.git
          git add .
          git commit -m "🚀 Auto-deploy Jekyll site"
          git push origin main
